function init(self)
    msg.post(nil, "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("mouse_press") and action.pressed == true then
		local x = action.x
		local y = action.y
		local loginnode = gui.get_node("login")
		local logoutnode = gui.get_node("logout")
		
		if gui.pick_node(loginnode, x, y) then
			msg.post("#script", "facebook_login")
		elseif gui.pick_node(logout, x, y) then
			msg.post("#script", "facebook_logout")
		end
	end
end
