embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 3.0\n"
  "friction: 0.3\n"
  "restitution: 0.7\n"
  "group: \"balls\"\n"
  "mask: \"player\"\n"
  "mask: \"world\"\n"
  "mask: \"locks\"\n"
  "mask: \"balls\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -0.13082999\n"
  "      y: -3.9248996\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 28.13992\n"
  "}\n"
  "angular_damping: 0.9\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"blue_star\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/physics_example/sprites.atlas\"\n"
  "}\n"
  ""
}
