flying = require "modules_example/flying"

function init(self)
	flying.fly_randomly()
end

function on_message(self, message_id, message, sender)
	if message_id == hash("fly_randomly_done") then
		flying.fly_randomly()
	end
end


function on_reload(self)
--	pprint(package.loaded["modules_example/flying"])
	package.loaded["modules_example/flying"] = nil
	flying = require "modules_example/flying"
end