function init(self)
	msg.post("#", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	if action_id == hash("mouse_press") and action.pressed == true then
		local x = action.x
		local y = action.y
		
		-- What buttons do we have.
		local buttons = { "button_ok", "button_cancel" }
		
		for i, b in ipairs(buttons) do
			if gui.pick_node(gui.get_node(b .. "/frame"), x, y) then
				print(b)
			end
		end
	end	
end
