function init(self)
    msg.post(nil, "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_message") then
		local node = gui.get_node("message")
		gui.set_text(node, message.text)
	elseif message_id == hash("set_payload") then
		local node = gui.get_node("payload")
		gui.set_text(node, message.payload)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("mouse_press") and action.pressed == true then
		local x = action.x
		local y = action.y
		local backnode = gui.get_node("local")
		
		-- Test if user has touched local button
		if gui.pick_node(backnode, x, y) then
			msg.post("push#script", "push_local")
		end
	end
end
